
import './globals.css'
import Navbar from './components/Navbar';
import { Inter } from "next/font/google";
// import { ThemeProvider } from 'next-themes';
import { getServerSession } from "next-auth";
import { SessionProvider } from 'next-auth/react';
import { UserProvider } from './utils/userContext';
import { ThemeProvider } from './context/ThemeContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
        <SessionProvider session={session}>
          <div className="mx-auto">
          <UserProvider>
            <Navbar />
            {children}
            </UserProvider>
          </div>
        </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
